project:
  type: website
  output-dir: _site

website:
  title: "life00"
  site-url: https://life00.github.io
  description: "Personal website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/life00
    search: true
  page-footer:
    left: "© 2026 life00"
    right:
      - icon: github
        href: https://github.com/life00

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
